# Generated by Django 3.1.4 on 2020-12-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicatingFile',
            fields=[
                ('communicating_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_scanned', models.DateTimeField()),
                ('detection_score', models.CharField(max_length=10)),
                ('severity', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'communicating_files',
                'db_table': 'communicating_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DomainIpScan',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
                ('severity', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'domain_ip_scans',
                'db_table': 'domain_ip_scans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutionParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(max_length=255)),
                ('date_scanned', models.DateTimeField()),
                ('detection_score', models.CharField(max_length=10)),
                ('severity', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'execution_parents',
                'db_table': 'execution_parents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileScan',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
                ('severity', models.CharField(max_length=10)),
                ('tags', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'file_scans',
                'db_table': 'file_scans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferringFile',
            fields=[
                ('referring_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_scanned', models.DateTimeField()),
                ('detection_score', models.CharField(max_length=10)),
                ('severity', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'referring_files',
                'db_table': 'referring_files',
                'managed': False,
            },
        ),
    ]
